apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: car-service
  template:
    metadata:
      labels:
        app: car-service
    spec:
      containers:
        - name: car-service
          image: "ds_lab3_car-service:latest"
          ports:
            - containerPort: 8082
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: car-service
spec:
  selector:
    app: car-service
  ports:
    - port: 8082
      targetPort: 8082
  type: ClusterIP
