apiVersion: apps/v1
kind: Deployment
metadata:
  name: location-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: location-service
  template:
    metadata:
      labels:
        app: location-service
    spec:
      containers:
        - name: location-service
          image: "ds_lab3_location-service:latest"
          ports:
            - containerPort: 8083
          imagePullPolicy: Never
          env:
            - name: SERVER_PORT
              value: "8083"
            - name: API_SECRET_KEY
              value: "my_secret_key"
            - name: USER_SERVICE_DOMAIN
              value: "user-service:8081"
            - name: CAR_SERVICE_DOMAIN
              value: "car-service:8082"
            - name: LOCATION_SERVICE_DOMAIN
              value: "location-service:8083"
            - name: ORDER_SERVICE_DOMAIN
              value: "order-service:8084"
---
apiVersion: v1
kind: Service
metadata:
  name: location-service
spec:
  selector:
    app: location-service
  ports:
    - port: 8083
      targetPort: 8083
  type: ClusterIP
