apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: "ds_lab3_server:latest"
          ports:
            - containerPort: 8090
          imagePullPolicy: Never
          env:
            - name: SERVER_PORT
              value: "8090"
            - name: API_SECRET_KEY
              value: "my_secret_key"
            - name: USER_SERVICE_DOMAIN
              value: "user-service:8081"
            - name: CAR_SERVICE_DOMAIN
              value: "car-service:8082"
            - name: LOCATION_SERVICE_DOMAIN
              value: "location-service:8083"
            - name: ORDER_SERVICE_DOMAIN
              value: "order-service:8084"
---
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  selector:
    app: server
  ports:
    - port: 8090
      targetPort: 8090
  type: LoadBalancer
