apiVersion: apps/v1
kind: Deployment
metadata:
    name: user-service-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: user-service
    template:
        metadata:
            labels:
                app: user-service
        spec:
            containers:
                - image: "ds_lab3_order-service:latest"
                  name: user-service
                  ports:
                      - containerPort: 8081
                  imagePullPolicy: Never
                  env:
                      - name: SERVER_PORT
                        value: "8081"
---
apiVersion: v1
kind: Service
metadata:
    name: user-service
spec:
    selector:
        app: user-service
    ports:
        - port: 8081
          targetPort: 8081
    type: ClusterIP
