apiVersion: apps/v1
kind: Deployment
metadata:
    name: user-service-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: user-service
    template:
        metadata:
            labels:
                app: user-service
        spec:
            containers:
                - image: "ds_lab3_order-service:latest"
                  name: user-service
                  ports:
                      - containerPort: 8081
                  imagePullPolicy: Never
                  env:
                      - name: SERVER_PORT
                        value: "8081"
                      - name: API_SECRET_KEY
                        value: "my_secret_key"
                      - name: USER_SERVICE_DOMAIN
                        value: "user-service:8081"
                      - name: CAR_SERVICE_DOMAIN
                        value: "car-service:8082"
                      - name: LOCATION_SERVICE_DOMAIN
                        value: "location-service:8083"
                      - name: ORDER_SERVICE_DOMAIN
                        value: "order-service:8084"
---
apiVersion: v1
kind: Service
metadata:
    name: user-service
spec:
    selector:
        app: user-service
    ports:
        - port: 8081
          targetPort: 8081
    type: ClusterIP
